version: "2"

services:
    nginx:
        container_name: nginx
        build: ./nginx
        links:
            - withsong:withsong
        ports:
            - 80:80
            - 443:443
        volumes: 
            - /data/nginx:/var/log/nginx
            - /etc/letsencrypt:/letsencrypt

    withsong:
        container_name: withsong
        build: .
        env_file: .env
        ports:
            - 8000
        links:
            - postgres:withsong_db
            - redis:withsong_redis
        volumes: 
            - /data/thumbnails:/usr/src/app/public/thumbnails
    postgres:
        container_name: postgres
        image: postgres:9.3
        ports:
            - 5432
        volumes: 
            - /data/postgres:/var/lib/postgresql/data
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379